[workspace]
exclude = ['lib']
members = ["nlib", "ru", "redis"]

[profile.release]
lto = true
opt-level = 3
incremental = true
codegen-units = 1
overflow-checks = false
panic = 'abort'
strip = true
debug-assertions = false

[registries.crates-io]
protocol = "sparse"
